# Generated by Django 2.2.6 on 2019-10-08 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição')], max_length=25, verbose_name='Status do projeto')),
                ('dt_avaliacao_responsavel', models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliação do responsável')),
                ('tem_introducao_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='A introdução está adequada?')),
                ('tem_justificativa_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Existe uma justificativa coerente?')),
                ('tem_objetivos_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Os objetivos são claros e exequíveis?')),
                ('tem_metodologia_desenho_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o desenho do estudo está claramente definido?')),
                ('tem_metodologia_local_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o local de realização do estudo e a população estão claramente definidos?')),
                ('tem_metodologia_amostra_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, há definição da amostra para estudos quantitativos?')),
                ('tem_metodologia_inclusao_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os critérios de inclusão e/ou exclusão estão claros?')),
                ('tem_metodologia_coleta_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o período de coleta de dados está definido?')),
                ('tem_metodologia_coleta_instrumento_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o projeto inclui um instrumento de coleta de dados em apêndice?')),
                ('tem_metodologia_etica_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os aspectos éticos estão descritos?')),
                ('tem_metodologia_riscos_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os riscos do estudo estão descritos?')),
                ('tem_metodologia_assentimento_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de assentimento em apêndice?')),
                ('tem_metodologia_consentimento_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de consentimento livre e esclarecido em apêndice?')),
                ('tem_metodologia_confidencialidade_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de confidencialidade?')),
                ('tem_metodologia_exequivel_estudo_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o projeto é exequível na instituição/unidade definido?')),
                ('tem_cronograma_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Há um cronograma de atividades?')),
                ('tem_orcamento_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Projeto possui orçamento?')),
                ('tem_orcamento_agencia_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O orçamento é de agência de fomento?')),
                ('tem_referencias_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Há referências bibliográficas no projeto?')),
                ('tem_assitencia_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto interfere na rotina ou prática assistencial vigente de modo significativo?')),
                ('tem_relevancia_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto tem relevância para a instituição envolvida?')),
                ('tem_mudanca_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê mudanças de alguma prática institucional vigente?')),
                ('tem_nova_pratica_assistencial_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê implementação de nova prática assistencial?')),
                ('tem_produto_responsavel', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê desenvolvimento de produto ou tecnologia leve-dura ou dura?')),
                ('parecer_avaliador_responsavel', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Parecer do avaliador responsável (2000 caracteres)')),
                ('dt_avaliacao_suplente', models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliação do suplente')),
                ('tem_introducao_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='A introdução está adequada?')),
                ('tem_justificativa_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Existe uma justificativa coerente?')),
                ('tem_objetivos_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Os objetivos são claros e exequíveis?')),
                ('tem_metodologia_desenho_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o desenho do estudo está claramente definido?')),
                ('tem_metodologia_local_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o local de realização do estudo e a população estão claramente definidos?')),
                ('tem_metodologia_amostra_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, há definição da amostra para estudos quantitativos?')),
                ('tem_metodologia_inclusao_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os critérios de inclusão e/ou exclusão estão claros?')),
                ('tem_metodologia_coleta_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o período de coleta de dados está definido?')),
                ('tem_metodologia_coleta_instrumento_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o projeto inclui um instrumento de coleta de dados em apêndice?')),
                ('tem_metodologia_etica_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os aspectos éticos estão descritos?')),
                ('tem_metodologia_riscos_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, os riscos do estudo estão descritos?')),
                ('tem_metodologia_assentimento_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de assentimento em apêndice?')),
                ('tem_metodologia_consentimento_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de consentimento livre e esclarecido em apêndice?')),
                ('tem_metodologia_confidencialidade_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, apresenta termo de confidencialidade?')),
                ('tem_metodologia_exequivel_estudo_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Metodologicamente, o projeto é exequível na instituição/unidade definido?')),
                ('tem_cronograma_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Há um cronograma de atividades?')),
                ('tem_orcamento_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Projeto possui orçamento?')),
                ('tem_orcamento_agencia_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O orçamento é de agência de fomento?')),
                ('tem_referencias_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='Há referências bibliográficas no projeto?')),
                ('tem_assitencia_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto interfere na rotina ou prática assistencial vigente de modo significativo?')),
                ('tem_relevancia_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto tem relevância para a instituição envolvida?')),
                ('tem_mudanca_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê mudanças de alguma prática institucional vigente?')),
                ('tem_nova_pratica_assistencial_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê implementação de nova prática assistencial?')),
                ('tem_produto_suplente', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('NÃO SE APLICA', 'Não se aplica')], max_length=25, null=True, verbose_name='O projeto prevê desenvolvimento de produto ou tecnologia leve-dura ou dura?')),
                ('parecer_avaliador_suplente', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Parecer do avaliador suplente (2000 caracteres)')),
                ('avaliador_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliador_responsavel', to=settings.AUTH_USER_MODEL)),
                ('avaliador_suplente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliador_suplente', to=settings.AUTH_USER_MODEL)),
                ('submissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submissao.Submissao')),
            ],
            options={
                'ordering': ['submissao', 'status'],
            },
        ),
    ]
