# Generated by Django 2.2.2 on 2019-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='dt_limite_avaliacao',
            field=models.DateTimeField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Data Limite para a avaliação'),
        ),
    ]
