# Generated by Django 2.2.6 on 2019-11-20 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_dt_limite_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliador_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Selecione um professor como avaliador responsável *'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliador_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Selecione um professor como avaliador suplente'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição')], default='EM ANÁLISE', max_length=25, verbose_name='Status do projeto'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='submissao',
            field=models.ForeignKey(help_text='Campo obrigatório como todos os que tiverem *', on_delete=django.db.models.deletion.PROTECT, to='submissao.Submissao', verbose_name='Selecione um projeto submetido para avaliação *'),
        ),
    ]
