# Generated by Django 2.2.6 on 2020-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_auto_20191120_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em análise'), ('EM EDIÇÃO', 'Em edição'), ('PENDENTE', 'Pendente'), ('PÓS CORREÇÃO', 'Pós correção')], default='EM ANÁLISE', max_length=25, verbose_name='Status do projeto'),
        ),
    ]
