# Generated by Django 2.2.6 on 2020-05-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_auto_20200521_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='dt_limite_avaliacao',
            field=models.DateTimeField(help_text='dd/mm/aaaa', verbose_name='Data Limite para a avaliação *'),
        ),
    ]
