# Generated by Django 2.2.13 on 2020-09-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_auto_20200904_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-dt_limite_avaliacao', 'submissao', 'comissao__status']},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='status',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='submissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='submissao.Submissao', verbose_name='Selecione um projeto submetido para avaliação *'),
        ),
    ]
