# Generated by Django 2.2.13 on 2020-10-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0008_auto_20200915_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-comissao__status', 'dt_limite_avaliacao', 'submissao']},
        ),
    ]
