# Generated by Django 2.2.13 on 2020-11-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_auto_20201031_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['comissao__status', 'dt_limite_avaliacao', 'submissao']},
        ),
    ]
