# Generated by Django 2.2.6 on 2019-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='abertura',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Abertura do edital *'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição *'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='encerra',
            field=models.DateField(help_text='dd/mm/aaaa', verbose_name='Encerramento do edital * '),
        ),
        migrations.AlterField(
            model_name='edital',
            name='numero',
            field=models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=20, verbose_name='Número do Edital *'),
        ),
    ]
