# Generated by Django 2.2.13 on 2021-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0002_auto_20191120_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['numero', 'abertura']},
        ),
    ]
