# Generated by Django 2.2.6 on 2019-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome *'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla *'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Site instituição *'),
        ),
    ]
