# Generated by Django 2.2.6 on 2019-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_auto_20191119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(help_text='Campo obrigatório como todos os que tiverem *', max_length=100, verbose_name='Nome *'),
        ),
    ]
