# Generated by Django 2.1.2 on 2019-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo padrão de resposta a submissão do projeto *'),
        ),
    ]
