# Generated by Django 2.2.6 on 2019-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0002_submissao_arquivo_resposta_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='curso_graduacao_vinculado',
            field=models.CharField(help_text='Nome dos cursos associados ao projeto separados por ponto-e-vírgula', max_length=100, verbose_name='Curso(s) de graduação vinculado(s) *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='curso_pos_graduacao',
            field=models.CharField(blank=True, help_text='Caso esteja vinculado', max_length=100, null=True, verbose_name='Curso(s) de pós-graduação vinculado(s)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='grupo_pesquisa',
            field=models.CharField(blank=True, help_text='Caso esteja vinculado ao projeto', max_length=50, null=True, verbose_name='Grupo de pesquisa vinculado'),
        ),
    ]
