# Generated by Django 2.2.6 on 2020-04-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0004_auto_20191120_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='arquivo_resposta_comissao',
        ),
    ]
