# Generated by Django 2.2.6 on 2020-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0005_remove_submissao_arquivo_resposta_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='arquivo_atualizacao_pendencia_projeto',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar seu projeto', null=True, upload_to='midias', verbose_name='Arquivo anexo de atualização de pendência do projeto *'),
        ),
    ]
