# Generated by Django 2.2.6 on 2020-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0006_submissao_arquivo_atualizacao_pendencia_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_atualizacao_pendencia_projeto',
            field=models.FileField(blank=True, help_text='ATENÇÃO: Depois de GRAVAR não será possível alterar!!', null=True, upload_to='midias', verbose_name='Arquivo anexo de atualização de pendência do projeto (Use arquivo .pdf para enviar seu projeto)'),
        ),
    ]
