# Generated by Django 2.2.13 on 2020-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0007_auto_20200522_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissao',
            options={'ordering': ['-edital', 'titulo', 'responsavel']},
        ),
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_atualizacao_pendencia_projeto',
            field=models.FileField(blank=True, help_text='ATENÇÃO: Depois de GRAVAR não será possível alterar!!', null=True, upload_to='midias', verbose_name='Arquivo da atualização de pendência do projeto (Use arquivo .pdf para enviar seu projeto)'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_projeto',
            field=models.FileField(help_text='Use arquivo .pdf para enviar seu projeto', upload_to='midias', verbose_name='Arquivo do projeto *'),
        ),
    ]
