# Generated by Django 2.2.13 on 2020-10-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0008_auto_20200711_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissao',
            options={'ordering': ['-edital', '-avaliacao__comissao__status', 'titulo', 'responsavel']},
        ),
        migrations.AddField(
            model_name='submissao',
            name='arquivo_anexo',
            field=models.FileField(blank=True, help_text='Quando carregar o anexo, faça registro no campo de Registros e Observações', null=True, upload_to='midias', verbose_name='Arquivo para anexos (pode ser compactado)'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='arquivo_comite_etica',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar a carta do Comitê de Ética', null=True, upload_to='midias', verbose_name='Arquivo do Comitê de Ética com a ciência do projeto'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='arquivo_parecer_substanciado',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar a carta do Comitê de Ética', null=True, upload_to='midias', verbose_name='Arquivo do Parecer Substanciado'),
        ),
        migrations.AddField(
            model_name='submissao',
            name='registros_apos_aprovacao',
            field=models.TextField(blank=True, help_text='Use este espaço empre que precisar registrar alguma alteração ou ponderar sobre algo', max_length=5000, null=True, verbose_name='Registros e observações no projeto após aprovação'),
        ),
    ]
