# Generated by Django 2.2.13 on 2020-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0009_auto_20201027_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='dt_atualizacao_submissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data que o projeto foi atualizado'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_parecer_substanciado',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para enviar o parecer substanciado', null=True, upload_to='midias', verbose_name='Arquivo do Parecer Substanciado'),
        ),
    ]
