# Generated by Django 3.1.5 on 2021-10-26 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0012_auto_20210329_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissao',
            options={'ordering': ['-edital', '-avaliacao__comissao__status', 'dt_cadastro_submissao', 'titulo', 'responsavel']},
        ),
        migrations.AddField(
            model_name='submissao',
            name='dt_cadastro_submissao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 26, 21, 36, 10, 259998, tzinfo=utc), verbose_name='Data que o projeto foi enviado'),
            preserve_default=False,
        ),
    ]
