# Generated by Django 3.1.5 on 2024-06-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0013_auto_20211026_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissao',
            options={'ordering': ['-edital__encerra', '-avaliacao__comissao__status', 'dt_cadastro_submissao', 'titulo']},
        ),
    ]
