# Generated by Django 2.2.6 on 2019-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191008_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PROFESSOR', 'Professor')], default='PROFESSOR', max_length=15, verbose_name='Tipo do usuário'),
        ),
    ]
