# Generated by Django 2.2.6 on 2019-11-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191119_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='RG'),
        ),
    ]
