# Generated by Django 2.2.6 on 2019-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191119_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Atenção: SOMENTE OS NÚMEROS', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituicao.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, help_text='Atenção: SOMENTE OS NÚMEROS', max_length=14, null=True, verbose_name='RG'),
        ),
    ]
