# Generated by Django 2.2.6 on 2020-02-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200226_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash'),
        ),
    ]
