# Generated by Django 2.2.6 on 2019-10-08 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer_comissao', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Parecer da comissão (2000 caracteres)')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('REPROVADO', 'Reprovado')], max_length=25, verbose_name='Status final do projeto')),
                ('dt_avaliacao_comissao', models.DateTimeField(blank=True, null=True, verbose_name='Data da avaliação da comissão')),
                ('avaliacao_comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.Avaliacao')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
