# Generated by Django 2.2.6 on 2019-11-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo padrão de resposta a submissão do projeto *'),
        ),
    ]
