# Generated by Django 2.2.6 on 2019-11-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_comissao_arquivo_resposta_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='parecer_comissao',
        ),
    ]
