# Generated by Django 2.2.6 on 2020-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0004_auto_20191120_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='arquivo2_resposta_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo de parecer depois pendência do projeto'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(help_text='Use arquivo .pdf para a resposta', upload_to='midias', verbose_name='Arquivo padrão de resposta à submissão do projeto *'),
        ),
    ]
