# Generated by Django 2.2.6 on 2020-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0005_auto_20200522_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_resposta_comissao',
            field=models.FileField(help_text='Use arquivo .pdf para a resposta', upload_to='midias', verbose_name='Arquivo inicial de resposta à submissão do projeto *'),
        ),
    ]
