# Generated by Django 2.2.6 on 2020-05-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0006_auto_20200522_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comissao',
            old_name='arquivo_resposta_comissao',
            new_name='arquivo1_resposta_comissao',
        ),
    ]
