# Generated by Django 2.2.6 on 2020-05-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0008_auto_20200522_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_parecer_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo inicial de resposta à submissão do projeto *'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('REPROVADO', 'Reprovado'), ('EM ANÁLISE', 'Em Análise')], max_length=25, verbose_name='Status final do projeto *'),
        ),
    ]
