# Generated by Django 2.2.13 on 2020-07-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0009_auto_20200523_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissao',
            options={'ordering': ['status', '-dt_avaliacao_comissao', 'avaliacao_comissao']},
        ),
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_parecer_comissao',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo inicial de resposta à submissão do projeto  (Use arquivo .pdf para enviar seu projeto) *'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='arquivo_parecer_comissao_pendencia',
            field=models.FileField(blank=True, help_text='Use arquivo .pdf para a resposta', null=True, upload_to='midias', verbose_name='Arquivo de parecer depois das correções solicitadas pela comissão  (Use arquivo .pdf para enviar seu projeto)'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='avaliacao_comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.Avaliacao', verbose_name='Selecione uma avaliação para parecer da comissão *'),
        ),
    ]
