# Generated by Django 2.2.13 on 2020-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0010_auto_20200711_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='comentario',
            field=models.TextField(blank=True, help_text='Digite todo e qualquer comentário ou anotação pertinente', null=True, verbose_name='Comentários'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='dt_trancado',
            field=models.DateField(blank=True, null=True, verbose_name='Data de trancamento do projeto'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('EM ANÁLISE', 'Em Análise'), ('PENDENTE', 'Pendente'), ('PÓS CORREÇÃO', 'Pós correção'), ('REPROVADO', 'Reprovado'), ('TRANCADO', 'Trancado')], default='EM ANÁLISE', max_length=25, verbose_name='Status final do projeto *'),
        ),
    ]
