# Generated by Django 2.2.13 on 2020-09-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0011_auto_20200904_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='avaliacao_comissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='avaliacao.Avaliacao', verbose_name='Selecione uma avaliação de projeto submetido para parecer da comissão *'),
        ),
    ]
